"""
A2A Message Dataclasses

WHY: Type-safe message definitions for agent-to-agent communication.
Each message type serves a specific purpose in the platform:
- SwarmQuery/Vote: RAG consensus mechanism
- JudgeEvaluate/Score: LLM-as-Judge quality checks
- AgentExecute/Result: Execution coordination

HOW: Uses Python dataclasses with JSON serialization for WebSocket transport.
"""
from dataclasses import dataclass, field, asdict
from typing import Any, Dict, List, Optional
from datetime import datetime
from enum import Enum
import uuid
import json


class MessageType(str, Enum):
    """Types of A2A messages"""
    # Swarm RAG messages
    SWARM_QUERY = "swarm.query"
    SWARM_VOTE = "swarm.vote"
    SWARM_CONSENSUS = "swarm.consensus"

    # Judge messages
    JUDGE_EVALUATE = "judge.evaluate"
    JUDGE_SCORE = "judge.score"

    # Execution messages
    AGENT_EXECUTE = "agent.execute"
    AGENT_RESULT = "agent.result"

    # Control messages
    AGENT_REGISTER = "agent.register"
    AGENT_HEARTBEAT = "agent.heartbeat"
    AGENT_DISCOVER = "agent.discover"


@dataclass
class A2AMessage:
    """
    Base A2A message structure.

    WHY: Common fields for all messages enable:
    - Correlation (tracking request/response pairs)
    - Routing (sender/target identification)
    - Timing (latency tracking)
    """
    message_type: MessageType
    sender_id: str
    target_id: Optional[str] = None  # None = broadcast
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    payload: Dict[str, Any] = field(default_factory=dict)

    def to_json(self) -> str:
        """Serialize to JSON for WebSocket transport"""
        data = asdict(self)
        data["message_type"] = self.message_type.value
        return json.dumps(data)

    @classmethod
    def from_json(cls, json_str: str) -> "A2AMessage":
        """Deserialize from JSON"""
        data = json.loads(json_str)
        data["message_type"] = MessageType(data["message_type"])
        return cls(**data)


@dataclass
class SwarmQueryMessage:
    """
    Query sent to RAG swarm agents for parallel search.

    WHY: Enables distributed search across multiple retrieval strategies:
    - Vector (semantic similarity)
    - Keyword (exact match)
    - Graph (relationship-based)
    - Metadata (field filtering)
    """
    query: str
    incident_id: str
    incident_type: str
    sender_id: str = "decision_orchestrator"
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    max_results: int = 10
    filters: Dict[str, Any] = field(default_factory=dict)

    def to_a2a(self) -> A2AMessage:
        """Convert to A2A message for transport"""
        return A2AMessage(
            message_type=MessageType.SWARM_QUERY,
            sender_id=self.sender_id,
            target_id=None,  # Broadcast to all swarm agents
            correlation_id=self.correlation_id,
            timestamp=self.timestamp,
            payload={
                "query": self.query,
                "incident_id": self.incident_id,
                "incident_type": self.incident_type,
                "max_results": self.max_results,
                "filters": self.filters,
            }
        )


@dataclass
class SwarmVoteMessage:
    """
    Vote from a RAG swarm agent with search results.

    WHY: Each agent votes with its results and confidence score.
    Consensus is reached by weighted aggregation of all votes.
    """
    agent_id: str
    agent_type: str  # vector, keyword, graph, metadata
    correlation_id: str
    results: List[Dict[str, Any]]
    confidence: float  # 0.0 - 1.0
    search_time_ms: float
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_a2a(self) -> A2AMessage:
        """Convert to A2A message for transport"""
        return A2AMessage(
            message_type=MessageType.SWARM_VOTE,
            sender_id=self.agent_id,
            target_id="swarm_aggregator",
            correlation_id=self.correlation_id,
            timestamp=self.timestamp,
            payload={
                "agent_type": self.agent_type,
                "results": self.results,
                "confidence": self.confidence,
                "search_time_ms": self.search_time_ms,
            }
        )


@dataclass
class JudgeEvaluateMessage:
    """
    Request for LLM-as-Judge to evaluate a generated plan.

    WHY: Uses a different LLM (Claude) to evaluate plans generated by
    the primary LLM (GPT-4), providing an independent quality check.
    This prevents single-model bias and improves reliability.
    """
    incident_id: str
    plan: Dict[str, Any]
    context: Dict[str, Any]  # Original incident + RAG results
    sender_id: str = "decision_orchestrator"
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_a2a(self) -> A2AMessage:
        """Convert to A2A message for transport"""
        return A2AMessage(
            message_type=MessageType.JUDGE_EVALUATE,
            sender_id=self.sender_id,
            target_id="llm_judge",
            correlation_id=self.correlation_id,
            timestamp=self.timestamp,
            payload={
                "incident_id": self.incident_id,
                "plan": self.plan,
                "context": self.context,
            }
        )


@dataclass
class JudgeScoreMessage:
    """
    Evaluation result from LLM-as-Judge.

    WHY: Multi-dimensional scoring enables nuanced routing:
    - Low safety → Immediate rejection
    - Low quality → Revision loop
    - High scores → Proceed to execution
    """
    correlation_id: str
    incident_id: str
    quality_score: float  # 1-10: Overall plan quality
    safety_passed: bool  # Binary: Is plan safe to execute?
    factual_score: float  # 1-10: Are facts correct?
    feasibility_score: float  # 1-10: Can this be executed?
    risk_level: str  # low, medium, high
    reasoning: str  # Explanation for scores
    suggested_improvements: List[str] = field(default_factory=list)
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_a2a(self) -> A2AMessage:
        """Convert to A2A message for transport"""
        return A2AMessage(
            message_type=MessageType.JUDGE_SCORE,
            sender_id="llm_judge",
            target_id="decision_orchestrator",
            correlation_id=self.correlation_id,
            timestamp=self.timestamp,
            payload={
                "incident_id": self.incident_id,
                "quality_score": self.quality_score,
                "safety_passed": self.safety_passed,
                "factual_score": self.factual_score,
                "feasibility_score": self.feasibility_score,
                "risk_level": self.risk_level,
                "reasoning": self.reasoning,
                "suggested_improvements": self.suggested_improvements,
            }
        )

    def should_approve(self) -> bool:
        """Determine if plan passes judge evaluation"""
        return (
            self.safety_passed and
            self.quality_score >= 6.0 and
            self.feasibility_score >= 5.0
        )


@dataclass
class AgentExecuteMessage:
    """
    Request for an execution agent to perform an action.

    WHY: Decouples planning from execution. The Execution Orchestrator
    sends execute messages to specialized agents (Terraform, Ansible, Code)
    which trigger GitHub Actions for actual infrastructure changes.
    """
    incident_id: str
    action_type: str  # terraform, ansible, code, restart
    action_payload: Dict[str, Any]
    approved_by: str  # Who approved this execution
    sender_id: str = "execution_orchestrator"
    target_agent: str = ""  # terraform_agent, ansible_agent, code_agent
    correlation_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())
    dry_run: bool = True  # Default to dry run for safety

    def to_a2a(self) -> A2AMessage:
        """Convert to A2A message for transport"""
        return A2AMessage(
            message_type=MessageType.AGENT_EXECUTE,
            sender_id=self.sender_id,
            target_id=self.target_agent,
            correlation_id=self.correlation_id,
            timestamp=self.timestamp,
            payload={
                "incident_id": self.incident_id,
                "action_type": self.action_type,
                "action_payload": self.action_payload,
                "approved_by": self.approved_by,
                "dry_run": self.dry_run,
            }
        )


@dataclass
class AgentResultMessage:
    """
    Result from an execution agent after performing an action.

    WHY: Provides feedback on execution success/failure, enabling:
    - State transitions in the workflow
    - Rollback triggering on failure
    - Learning from execution outcomes
    """
    correlation_id: str
    incident_id: str
    agent_id: str
    status: str  # success, failed, partial, rollback_needed
    execution_time_ms: float
    output: Dict[str, Any]
    error: Optional[str] = None
    rollback_available: bool = False
    github_run_id: Optional[str] = None  # GitHub Actions run ID
    timestamp: str = field(default_factory=lambda: datetime.utcnow().isoformat())

    def to_a2a(self) -> A2AMessage:
        """Convert to A2A message for transport"""
        return A2AMessage(
            message_type=MessageType.AGENT_RESULT,
            sender_id=self.agent_id,
            target_id="execution_orchestrator",
            correlation_id=self.correlation_id,
            timestamp=self.timestamp,
            payload={
                "incident_id": self.incident_id,
                "status": self.status,
                "execution_time_ms": self.execution_time_ms,
                "output": self.output,
                "error": self.error,
                "rollback_available": self.rollback_available,
                "github_run_id": self.github_run_id,
            }
        )
