"""
Bronze Layer Ingest Spark Job
Domain: sales
Source: GCS landing zone
Target: Delta table in bronze layer

Generated by: Data Agent
Purpose: Ingest raw data with audit columns and minimal transformation
"""

import sys
from datetime import datetime
from typing import Optional

from pyspark.sql import SparkSession, DataFrame
from pyspark.sql import functions as F
from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    IntegerType,
    LongType,
    DoubleType,
    BooleanType,
    TimestampType,
    DateType,
    DecimalType,
)
import logging
import argparse

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("bronze_ingest")


def get_schema() -> StructType:
    """
    Returns the schema for sales data.
    """
    return StructType([
        StructField("order_id", StringType(), False),
        StructField("customer_id", StringType(), False),
        StructField("product_id", StringType(), False),
        StructField("quantity", IntegerType(), True),
        StructField("unit_price", DoubleType(), True),
        StructField("total_amount", DoubleType(), True),
        StructField("order_date", DateType(), True),
        StructField("ship_date", DateType(), True),
        StructField("status", StringType(), True),
        StructField("region", StringType(), True),
    ])


def read_source_data(
    spark: SparkSession,
    source_path: str,
    file_format: str = "parquet",
    schema: Optional[StructType] = None,
) -> DataFrame:
    """
    Read data from source path.
    """
    logger.info(f"Reading {file_format} data from {source_path}")

    reader = spark.read

    if schema:
        reader = reader.schema(schema)

    if file_format == "parquet":
        df = reader.parquet(source_path)
    elif file_format == "csv":
        df = reader.option("header", "true") \
                   .option("inferSchema", "false" if schema else "true") \
                   .option("mode", "PERMISSIVE") \
                   .option("columnNameOfCorruptRecord", "_corrupt_record") \
                   .csv(source_path)
    elif file_format == "json":
        df = reader.option("mode", "PERMISSIVE") \
                   .option("columnNameOfCorruptRecord", "_corrupt_record") \
                   .json(source_path)
    else:
        raise ValueError(f"Unsupported file format: {file_format}")

    record_count = df.count()
    logger.info(f"Read {record_count} records from source")

    return df


def add_audit_columns(
    df: DataFrame,
    batch_id: str,
    source_path: str,
) -> DataFrame:
    """
    Add audit columns to DataFrame.
    """
    logger.info("Adding audit columns")

    data_columns = [F.col(c).cast("string") for c in df.columns]

    return df.withColumn("_ingested_at", F.current_timestamp()) \
             .withColumn("_source_file", F.lit(source_path)) \
             .withColumn("_batch_id", F.lit(batch_id)) \
             .withColumn("_row_hash", F.sha2(F.concat_ws("|", *data_columns), 256))


def validate_data(df: DataFrame, spark: SparkSession) -> tuple:
    """
    Validate data and separate valid from invalid records.
    """
    logger.info("Validating data quality")

    if "_corrupt_record" in df.columns:
        valid_df = df.filter(F.col("_corrupt_record").isNull()) \
                     .drop("_corrupt_record")
        invalid_df = df.filter(F.col("_corrupt_record").isNotNull())

        invalid_count = invalid_df.count()
        if invalid_count > 0:
            logger.warning(f"Found {invalid_count} corrupt records")
    else:
        valid_df = df
        invalid_df = spark.createDataFrame([], df.schema)

    return valid_df, invalid_df


def write_to_bronze(
    df: DataFrame,
    table_path: str,
    partition_columns: list = None,
    mode: str = "append",
) -> None:
    """
    Write DataFrame to bronze Delta table.
    """
    logger.info(f"Writing to bronze path: {table_path}")

    writer = df.write.format("delta").mode(mode)

    if partition_columns:
        writer = writer.partitionBy(*partition_columns)

    writer.option("mergeSchema", "true").save(table_path)

    logger.info(f"Successfully wrote to {table_path}")


def main():
    """Main entry point for bronze ingest."""

    parser = argparse.ArgumentParser(description="Bronze layer ingest job")
    parser.add_argument("--source-path", required=True, help="Source data path")
    parser.add_argument("--batch-id", required=True, help="Batch identifier")
    parser.add_argument("--execution-date", help="Execution date (YYYY-MM-DD)")
    parser.add_argument("--file-format", default="parquet", help="Source file format")
    args = parser.parse_args()

    config = {
        "pipeline_name": "sales_bronze",
        "domain": "sales",
        "bronze_path": "gs://data-agent-bronze/sales",
        "file_format": args.file_format,
        "partition_columns": ["_ingested_at"],
        "source_path": args.source_path,
        "batch_id": args.batch_id,
    }

    logger.info(f"Starting bronze ingest")
    logger.info(f"Configuration: {config}")

    spark = SparkSession.builder \
        .appName(f"bronze_ingest_{config['batch_id']}") \
        .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
        .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
        .config("spark.databricks.delta.schema.autoMerge.enabled", "true") \
        .getOrCreate()

    try:
        schema = get_schema()

        df = read_source_data(
            spark=spark,
            source_path=config["source_path"],
            file_format=config["file_format"],
            schema=schema,
        )

        valid_df, invalid_df = validate_data(df, spark)

        bronze_df = add_audit_columns(
            df=valid_df,
            batch_id=config["batch_id"],
            source_path=config["source_path"],
        )

        write_to_bronze(
            df=bronze_df,
            table_path=config["bronze_path"],
            partition_columns=config["partition_columns"],
        )

        metrics = {
            "records_read": df.count(),
            "records_valid": valid_df.count(),
            "records_invalid": invalid_df.count(),
            "batch_id": config["batch_id"],
        }
        logger.info(f"Bronze ingest complete. Metrics: {metrics}")

        return metrics

    except Exception as e:
        logger.error(f"Bronze ingest failed: {str(e)}", exc_info=True)
        raise
    finally:
        spark.stop()


if __name__ == "__main__":
    main()
