"""
Gold Layer - Load to BigQuery
Domain: sales
Source: Silver Delta table
Target: BigQuery table

Generated by: Data Agent
Purpose: Aggregate data and load to BigQuery for analytics
"""

from pyspark.sql import SparkSession, DataFrame
from pyspark.sql import functions as F
import logging
import argparse

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("gold_load_bq")


def read_silver(spark: SparkSession, silver_path: str, batch_id: str = None) -> DataFrame:
    """Read data from silver layer."""
    logger.info(f"Reading from silver: {silver_path}")

    df = spark.read.format("delta").load(silver_path)

    if batch_id:
        df = df.filter(F.col("_batch_id") == batch_id)

    logger.info(f"Read {df.count()} records from silver")
    return df


def create_daily_summary(df: DataFrame) -> DataFrame:
    """Create daily sales summary aggregations."""
    logger.info("Creating daily sales summary")

    summary = df.groupBy(
        "order_date",
        "region"
    ).agg(
        F.count("order_id").alias("total_orders"),
        F.countDistinct("customer_id").alias("unique_customers"),
        F.sum("quantity").alias("total_quantity"),
        F.sum("total_amount").alias("total_revenue"),
        F.avg("total_amount").alias("avg_order_value"),
        F.min("total_amount").alias("min_order_value"),
        F.max("total_amount").alias("max_order_value"),
        F.avg("days_to_ship").alias("avg_days_to_ship"),
        F.sum(F.when(F.col("is_high_value"), 1).otherwise(0)).alias("high_value_orders"),
    ).withColumn("_loaded_at", F.current_timestamp())

    logger.info(f"Created {summary.count()} summary records")
    return summary


def create_product_summary(df: DataFrame) -> DataFrame:
    """Create product performance summary."""
    logger.info("Creating product summary")

    summary = df.groupBy(
        "product_id",
        "order_year",
        "order_month"
    ).agg(
        F.count("order_id").alias("order_count"),
        F.sum("quantity").alias("total_quantity_sold"),
        F.sum("total_amount").alias("total_revenue"),
        F.avg("unit_price").alias("avg_unit_price"),
        F.countDistinct("customer_id").alias("unique_customers"),
    ).withColumn("_loaded_at", F.current_timestamp())

    return summary


def write_to_bigquery(
    df: DataFrame,
    project_id: str,
    dataset: str,
    table: str,
    mode: str = "append"
) -> None:
    """Write DataFrame to BigQuery."""
    full_table = f"{project_id}.{dataset}.{table}"
    logger.info(f"Writing to BigQuery: {full_table}")

    df.write \
        .format("bigquery") \
        .option("table", full_table) \
        .option("temporaryGcsBucket", f"{project_id}-temp") \
        .mode(mode) \
        .save()

    logger.info(f"Successfully wrote to {full_table}")


def write_to_gold_delta(df: DataFrame, gold_path: str, partition_columns: list = None) -> None:
    """Also write to gold Delta table for data lineage."""
    logger.info(f"Writing to gold Delta: {gold_path}")

    writer = df.write.format("delta").mode("append")
    if partition_columns:
        writer = writer.partitionBy(*partition_columns)

    writer.save(gold_path)


def main():
    parser = argparse.ArgumentParser(description="Gold layer - Load to BigQuery")
    parser.add_argument("--batch-id", required=True, help="Batch identifier")
    parser.add_argument("--execution-date", help="Execution date")
    parser.add_argument("--target-dataset", default="gold_sales", help="BigQuery dataset")
    parser.add_argument("--target-table", default="daily_sales_summary", help="BigQuery table")
    args = parser.parse_args()

    # Get project ID from environment or default
    import os
    project_id = os.getenv("GCP_PROJECT_ID", "your-gcp-project")

    config = {
        "silver_path": "gs://data-agent-silver/sales",
        "gold_path": "gs://data-agent-gold/sales",
        "project_id": project_id,
        "dataset": args.target_dataset,
        "table": args.target_table,
        "batch_id": args.batch_id,
    }

    logger.info(f"Starting gold layer load to BigQuery")
    logger.info(f"Configuration: {config}")

    spark = SparkSession.builder \
        .appName(f"gold_load_bq_{config['batch_id']}") \
        .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
        .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
        .getOrCreate()

    try:
        # Read silver data
        silver_df = read_silver(spark, config["silver_path"], config["batch_id"])

        # Create daily summary
        daily_summary = create_daily_summary(silver_df)

        # Write to BigQuery
        write_to_bigquery(
            df=daily_summary,
            project_id=config["project_id"],
            dataset=config["dataset"],
            table=config["table"],
        )

        # Also write to gold Delta for lineage
        write_to_gold_delta(
            df=daily_summary,
            gold_path=f"{config['gold_path']}/daily_summary",
            partition_columns=["order_date"]
        )

        # Create and write product summary
        product_summary = create_product_summary(silver_df)
        write_to_bigquery(
            df=product_summary,
            project_id=config["project_id"],
            dataset=config["dataset"],
            table="product_summary",
        )

        metrics = {
            "daily_summary_records": daily_summary.count(),
            "product_summary_records": product_summary.count(),
            "batch_id": config["batch_id"],
        }
        logger.info(f"Gold load complete. Metrics: {metrics}")

    except Exception as e:
        logger.error(f"Gold load failed: {str(e)}", exc_info=True)
        raise
    finally:
        spark.stop()


if __name__ == "__main__":
    main()
