"""
Silver Layer Transform Spark Job
Domain: sales
Source: Bronze Delta table
Target: Silver Delta table (cleaned and validated)

Generated by: Data Agent
Purpose: Clean, deduplicate, and apply business rules
"""

from pyspark.sql import SparkSession, DataFrame
from pyspark.sql import functions as F
from pyspark.sql.window import Window
import logging
import argparse

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("silver_transform")


def read_bronze(spark: SparkSession, bronze_path: str, batch_id: str = None) -> DataFrame:
    """Read data from bronze layer."""
    logger.info(f"Reading from bronze: {bronze_path}")

    df = spark.read.format("delta").load(bronze_path)

    if batch_id:
        df = df.filter(F.col("_batch_id") == batch_id)
        logger.info(f"Filtered to batch_id: {batch_id}")

    logger.info(f"Read {df.count()} records from bronze")
    return df


def deduplicate(df: DataFrame, key_columns: list, order_column: str = "_ingested_at") -> DataFrame:
    """Remove duplicates keeping the latest record."""
    logger.info(f"Deduplicating on keys: {key_columns}")

    window = Window.partitionBy(key_columns).orderBy(F.col(order_column).desc())

    deduped = df.withColumn("_rank", F.row_number().over(window)) \
                .filter(F.col("_rank") == 1) \
                .drop("_rank")

    original_count = df.count()
    deduped_count = deduped.count()
    logger.info(f"Deduplicated: {original_count} -> {deduped_count} ({original_count - deduped_count} removed)")

    return deduped


def clean_data(df: DataFrame) -> DataFrame:
    """Apply data cleaning transformations."""
    logger.info("Applying data cleaning rules")

    cleaned = df \
        .withColumn("order_id", F.trim(F.upper(F.col("order_id")))) \
        .withColumn("customer_id", F.trim(F.col("customer_id"))) \
        .withColumn("product_id", F.trim(F.col("product_id"))) \
        .withColumn("status", F.upper(F.trim(F.col("status")))) \
        .withColumn("region", F.upper(F.trim(F.col("region")))) \
        .filter(F.col("order_id").isNotNull()) \
        .filter(F.col("customer_id").isNotNull()) \
        .filter(F.col("quantity") > 0) \
        .filter(F.col("total_amount") >= 0)

    logger.info(f"After cleaning: {cleaned.count()} records")
    return cleaned


def enrich_data(df: DataFrame) -> DataFrame:
    """Add derived columns and enrichments."""
    logger.info("Enriching data")

    enriched = df \
        .withColumn("order_year", F.year(F.col("order_date"))) \
        .withColumn("order_month", F.month(F.col("order_date"))) \
        .withColumn("order_quarter", F.quarter(F.col("order_date"))) \
        .withColumn("days_to_ship",
            F.when(F.col("ship_date").isNotNull(),
                   F.datediff(F.col("ship_date"), F.col("order_date")))
            .otherwise(None)) \
        .withColumn("is_high_value", F.col("total_amount") >= 1000) \
        .withColumn("_processed_at", F.current_timestamp())

    return enriched


def write_to_silver(df: DataFrame, silver_path: str, partition_columns: list = None) -> None:
    """Write to silver Delta table."""
    logger.info(f"Writing to silver: {silver_path}")

    writer = df.write.format("delta").mode("append")

    if partition_columns:
        writer = writer.partitionBy(*partition_columns)

    writer.option("mergeSchema", "true").save(silver_path)
    logger.info("Silver write complete")


def main():
    parser = argparse.ArgumentParser(description="Silver layer transform job")
    parser.add_argument("--batch-id", required=True, help="Batch identifier")
    parser.add_argument("--execution-date", help="Execution date")
    args = parser.parse_args()

    config = {
        "bronze_path": "gs://data-agent-bronze/sales",
        "silver_path": "gs://data-agent-silver/sales",
        "key_columns": ["order_id"],
        "partition_columns": ["order_year", "order_month"],
        "batch_id": args.batch_id,
    }

    logger.info(f"Starting silver transform")
    logger.info(f"Configuration: {config}")

    spark = SparkSession.builder \
        .appName(f"silver_transform_{config['batch_id']}") \
        .config("spark.sql.extensions", "io.delta.sql.DeltaSparkSessionExtension") \
        .config("spark.sql.catalog.spark_catalog", "org.apache.spark.sql.delta.catalog.DeltaCatalog") \
        .getOrCreate()

    try:
        # Read bronze data
        bronze_df = read_bronze(spark, config["bronze_path"], config["batch_id"])

        # Deduplicate
        deduped_df = deduplicate(bronze_df, config["key_columns"])

        # Clean data
        cleaned_df = clean_data(deduped_df)

        # Enrich data
        silver_df = enrich_data(cleaned_df)

        # Write to silver
        write_to_silver(silver_df, config["silver_path"], config["partition_columns"])

        metrics = {
            "records_input": bronze_df.count(),
            "records_output": silver_df.count(),
            "batch_id": config["batch_id"],
        }
        logger.info(f"Silver transform complete. Metrics: {metrics}")

    except Exception as e:
        logger.error(f"Silver transform failed: {str(e)}", exc_info=True)
        raise
    finally:
        spark.stop()


if __name__ == "__main__":
    main()
