"""
APEX Data Agent — Governance Enforcer

Enforces data governance policies:
1. PII masking based on platform_data_classification table
2. BigQuery policy tag generation
3. Access policy validation

Bridges the gap between PII detection (detection) and actual enforcement (masking/tagging).
"""

import json
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional, Tuple

import structlog
from pyspark.sql import DataFrame

logger = structlog.get_logger()


class GovernanceEnforcer:
    """
    Enforces governance policies on data in transit.

    Flow:
    1. PII detection runs → results stored in platform_data_classification
    2. GovernanceEnforcer reads classifications → applies masking
    3. Also generates BigQuery policy tag DDL for downstream access control
    """

    def __init__(self, connection_string: Optional[str] = None):
        """Initialize with PostgreSQL connection."""
        import psycopg2
        import os

        conn_str = connection_string or os.getenv("APEX_METADATA_DB_URL")
        self.conn = psycopg2.connect(conn_str)

    # ═══════════════════════════════════════════════════════════════════════
    # PII MASKING ENFORCEMENT
    # ═══════════════════════════════════════════════════════════════════════

    def enforce_pii_masking(
        self,
        df: DataFrame,
        asset_id: Optional[str] = None,
        classifications: Optional[List[Dict]] = None,
    ) -> Tuple[DataFrame, int]:
        """
        Apply masking transforms based on platform_data_classification records.

        Args:
            df: Input Spark DataFrame
            asset_id: Asset ID to look up classifications (if not provided directly)
            classifications: Pre-loaded classification records

        Returns:
            Tuple of (masked DataFrame, number of columns masked)
        """
        from security.pii_detection import PIIMasker, MaskingStrategy, PIIType

        if classifications is None and asset_id:
            classifications = self.get_classifications(asset_id)

        if not classifications:
            return df, 0

        masked_df = df
        columns_masked = 0

        for cls in classifications:
            column_name = cls["column_name"]
            if column_name not in df.columns:
                continue

            strategy_str = cls.get("masking_strategy", "HASH")
            pii_type_str = cls.get("pii_type", "NAME")

            try:
                strategy = MaskingStrategy(strategy_str.lower())
                pii_type = PIIType(pii_type_str.lower())
            except ValueError:
                strategy = MaskingStrategy.HASH
                pii_type = PIIType.NAME

            masked_df = PIIMasker.mask_column(masked_df, column_name, strategy, pii_type)
            columns_masked += 1

            logger.info(
                "governance_column_masked",
                column=column_name,
                strategy=strategy_str,
                pii_type=pii_type_str,
            )

        return masked_df, columns_masked

    def get_classifications(self, asset_id: str) -> List[Dict[str, Any]]:
        """Load active classifications for an asset."""
        query = """
            SELECT column_name, classification_type, pii_type,
                   confidence, masking_strategy, policy_tag, is_enforced
            FROM platform_data_classification
            WHERE asset_id = %s
            ORDER BY column_name
        """
        with self.conn.cursor() as cur:
            cur.execute(query, [asset_id])
            columns = [desc[0] for desc in cur.description]
            return [dict(zip(columns, row)) for row in cur.fetchall()]

    # ═══════════════════════════════════════════════════════════════════════
    # BIGQUERY POLICY TAG GENERATION
    # ═══════════════════════════════════════════════════════════════════════

    def generate_bq_policy_tags(
        self,
        asset_id: str,
        project_id: str,
        taxonomy_id: str = "apex_data_classification",
    ) -> str:
        """
        Generate BigQuery policy tag DDL from data classifications.

        Returns SQL that creates policy tags and applies them to columns.
        """
        classifications = self.get_classifications(asset_id)
        if not classifications:
            return "-- No classifications found for this asset"

        # Group by classification type for taxonomy
        lines = [
            f"-- Auto-generated by APEX GovernanceEnforcer",
            f"-- Asset ID: {asset_id}",
            f"-- Generated: {datetime.utcnow().isoformat()}Z",
            f"",
            f"-- Create taxonomy (run once)",
            f"-- bq mk --taxonomy --description 'APEX Data Classification' "
            f"--location US {project_id}:{taxonomy_id}",
            f"",
        ]

        # Group columns by classification type
        by_type: Dict[str, List[str]] = {}
        for cls in classifications:
            ct = cls["classification_type"]
            if ct not in by_type:
                by_type[ct] = []
            by_type[ct].append(cls["column_name"])

        for cls_type, columns in by_type.items():
            tag_name = cls_type.lower()
            lines.append(f"-- Policy tag: {tag_name}")
            lines.append(
                f"-- bq mk --policy_tag --taxonomy {project_id}:{taxonomy_id} "
                f"--description '{cls_type} columns' {tag_name}"
            )
            for col_name in columns:
                lines.append(f"--   Column: {col_name}")
            lines.append("")

        # Generate ALTER TABLE statements for column-level policy tags
        lines.append("-- Apply policy tags to BigQuery columns:")
        for cls in classifications:
            policy_tag = cls.get("policy_tag") or cls["classification_type"].lower()
            lines.append(
                f"ALTER TABLE `{{{{dataset}}}}.{{{{table}}}}` "
                f"ALTER COLUMN {cls['column_name']} "
                f"SET OPTIONS (policy_tags=['projects/{project_id}/"
                f"locations/us/taxonomies/{taxonomy_id}/policyTags/{policy_tag}']);"
            )

        return "\n".join(lines)

    # ═══════════════════════════════════════════════════════════════════════
    # ACCESS POLICY VALIDATION
    # ═══════════════════════════════════════════════════════════════════════

    def check_access(
        self,
        principal_id: str,
        principal_type: str,
        resource_id: str,
        resource_type: str,
        required_level: str = "READ",
    ) -> bool:
        """
        Check if a principal has access to a resource.

        Args:
            principal_id: User/group/service account identifier
            principal_type: USER, GROUP, SERVICE_ACCOUNT
            resource_id: Resource identifier (table path, dataset name)
            resource_type: DATASET, TABLE, COLUMN, ZONE, DOMAIN
            required_level: Required access level (READ, WRITE, ADMIN)

        Returns:
            True if access is granted
        """
        # Access level hierarchy: ADMIN > WRITE > READ > MASKED_READ
        level_hierarchy = {"MASKED_READ": 0, "READ": 1, "WRITE": 2, "ADMIN": 3}
        required_rank = level_hierarchy.get(required_level, 1)

        query = """
            SELECT access_level FROM platform_access_policy
            WHERE principal_id = %s
              AND principal_type = %s
              AND resource_id = %s
              AND resource_type = %s
              AND is_active = true
              AND (expires_at IS NULL OR expires_at > now())
            ORDER BY access_level DESC
            LIMIT 1
        """
        with self.conn.cursor() as cur:
            cur.execute(query, [principal_id, principal_type, resource_id, resource_type])
            row = cur.fetchone()
            if row:
                granted_rank = level_hierarchy.get(row[0], 0)
                return granted_rank >= required_rank

        return False

    def get_masked_columns(self, principal_id: str, asset_id: str) -> List[str]:
        """
        Get columns that should be masked for a specific principal.

        Returns columns where the principal only has MASKED_READ access
        or where PII is classified and not explicitly granted.
        """
        query = """
            SELECT dc.column_name
            FROM platform_data_classification dc
            WHERE dc.asset_id = %s
              AND dc.classification_type IN ('PII', 'PHI')
              AND dc.column_name NOT IN (
                  SELECT ap.resource_id FROM platform_access_policy ap
                  WHERE ap.principal_id = %s
                    AND ap.resource_type = 'COLUMN'
                    AND ap.access_level IN ('READ', 'WRITE', 'ADMIN')
                    AND ap.is_active = true
              )
        """
        with self.conn.cursor() as cur:
            cur.execute(query, [asset_id, principal_id])
            return [row[0] for row in cur.fetchall()]
