"""
ebcdic_customer_pipeline - Enterprise Data Pipeline

Domain: customer
Product: Customer Master from Mainframe
Environment: dev
Source: file_ebcdic (ebcdic_copybook)
Schedule: @daily

PIPELINE FLOW:
┌─────────────┐    ┌─────────────┐    ┌─────────────┐    ┌─────────────┐    ┌─────────────┐
│   LANDING   │ →  │   BRONZE    │ →  │   SILVER    │ →  │    GOLD     │ →  │   TRUSTED   │
│  (Validate) │    │  (Ingest)   │    │ (Transform) │    │ (Aggregate) │    │  (Publish)  │
└─────────────┘    └─────────────┘    └─────────────┘    └─────────────┘    └─────────────┘

TASK GROUPS:
1. pre_checks: File sensing, schema validation, contract verification
2. landing_zone: Raw file validation and staging
3. bronze_zone: Raw data ingestion with typing
4. silver_zone: Cleansing, dedup, transformation, DQ checks
5. gold_zone: Aggregation, business metrics
6. trusted_zone: Publication to targets, certification
7. post_processing: Audit logging, notifications, cleanup
8. quality_gate: DQ scoring and gate decisions
9. self_healing: Automatic error recovery

Generated by: Data Agent (Enterprise Template)
Jira: DATA-5678
"""

from datetime import datetime, timedelta
from typing import Any, Dict, List, Optional

from airflow import DAG
from airflow.decorators import task, task_group
from airflow.models import Variable
from airflow.operators.empty import EmptyOperator
from airflow.operators.python import PythonOperator, BranchPythonOperator, ShortCircuitOperator
from airflow.providers.google.cloud.operators.dataproc import (
    DataprocSubmitJobOperator,
    DataprocCreateClusterOperator,
    DataprocDeleteClusterOperator,
)
from airflow.providers.google.cloud.sensors.gcs import GCSObjectsWithPrefixExistenceSensor
from airflow.providers.google.cloud.transfers.gcs_to_gcs import GCSToGCSOperator
from airflow.providers.google.cloud.hooks.gcs import GCSHook
from airflow.utils.task_group import TaskGroup
from airflow.utils.trigger_rule import TriggerRule
from airflow.exceptions import AirflowSkipException, AirflowFailException


# =============================================================================
# Configuration
# =============================================================================

# GCP Configuration
PROJECT_ID = "{{ var.value.gcp_project_id }}"
REGION = "{{ var.value.gcp_region }}"
DATAPROC_CLUSTER = "{{ var.value.dataproc_cluster }}"
SERVICE_ACCOUNT = "{{ var.value.dataproc_service_account }}"

# Product Configuration
PRODUCT_CODE = "cust_master_ebcdic"
DOMAIN = "customer"
ENVIRONMENT = "dev"

# Paths
LANDING_PATH = "gs://landing-mainframe/customer/"
BRONZE_PATH = "gs://bronze/cust_master_ebcdic"
SILVER_PATH = "gs://silver/cust_master_ebcdic"
GOLD_PATH = "gs://gold/cust_master_ebcdic"
TRUSTED_PATH = "gs://trusted/cust_master_ebcdic"
REJECTED_PATH = "gs://rejected/cust_master_ebcdic"
ARCHIVE_PATH = "gs://archive/cust_master_ebcdic"

# Spark Job URIs (deployed to GCS)
SPARK_JOBS = {
    "bronze_ingest": "gs://spark-jobs/cust_master_ebcdic/bronze_ingest.py",
    "silver_transform": "gs://spark-jobs/cust_master_ebcdic/silver_transform.py",
    "gold_aggregate": "gs://spark-jobs/cust_master_ebcdic/gold_aggregate.py",
    "quality_validate": "gs://spark-jobs/cust_master_ebcdic/quality_validate.py",
    "trusted_publish": "gs://spark-jobs/cust_master_ebcdic/trusted_publish.py",
}

# Processing Configuration
PROCESSING_MODE = "batch_incremental"
LOAD_STRATEGY = "merge_upsert"
PRIMARY_KEYS = ["cust_id"]
PARTITION_COLUMNS = ["_ingested_date"]
WATERMARK_COLUMN = ""

# Quality Configuration
MIN_QUALITY_SCORE = 85.0
BLOCK_ON_QUALITY_FAILURE = True
QUALITY_RULES = [{"column": "cust_id", "rule": "not_null", "severity": "critical"}, {"column": "cust_id", "rule": "unique", "severity": "critical"}]

# Self-Healing Configuration
SELF_HEALING_ENABLED = True
MAX_HEALING_ATTEMPTS = 3

# Targets Configuration
TARGETS = []

# Source-specific Configuration
SOURCE_CONFIG = {}

# Spark Configurations per Zone
SPARK_BRONZE_CONFIG = {"driver_memory": "2g", "executor_cores": 2, "executor_instances": 2, "executor_memory": "4g"}

SPARK_SILVER_CONFIG = {"driver_memory": "4g", "executor_cores": 4, "executor_instances": 4, "executor_memory": "8g"}

SPARK_GOLD_CONFIG = {"driver_memory": "4g", "executor_cores": 4, "executor_instances": 4, "executor_memory": "8g"}

# Alerting
ALERT_EMAILS = ["data-team@example.com"]
SLACK_WEBHOOK = ""
PAGERDUTY_KEY = ""


# =============================================================================
# Default Arguments
# =============================================================================

default_args = {
    "owner": "mainframe-migration-team",
    "depends_on_past": False,
    "email": ALERT_EMAILS,
    "email_on_failure": True,
    "email_on_retry": False,
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
    "execution_timeout": timedelta(hours=2),
    "sla": timedelta(hours=4),
}


# =============================================================================
# Helper Functions
# =============================================================================


def _build_spark_job(
    job_uri: str,
    args: List[str],
    spark_config: Dict[str, Any],
) -> dict:
    """Build Dataproc PySpark job configuration."""
    return {
        "placement": {"cluster_name": DATAPROC_CLUSTER},
        "pyspark_job": {
            "main_python_file_uri": job_uri,
            "args": args,
            "properties": {
                "spark.executor.instances": str(spark_config.get("executor_instances", 2)),
                "spark.executor.memory": spark_config.get("executor_memory", "4g"),
                "spark.executor.cores": str(spark_config.get("executor_cores", 2)),
                "spark.driver.memory": spark_config.get("driver_memory", "2g"),
                "spark.sql.adaptive.enabled": "true",
                "spark.sql.adaptive.coalescePartitions.enabled": "true",
                "spark.databricks.delta.schema.autoMerge.enabled": "true",
                **spark_config.get("custom_properties", {}),
            },
        },
    }


def _send_slack_notification(context: Dict[str, Any], message: str):
    """Send Slack notification."""
    if not SLACK_WEBHOOK:
        return

    import requests

    payload = {
        "text": f"*{PRODUCT_CODE}* ({ENVIRONMENT})\n{message}",
        "attachments": [
            {
                "color": "#ff0000" if "failed" in message.lower() else "#36a64f",
                "fields": [
                    {"title": "DAG", "value": context.get("dag").dag_id, "short": True},
                    {"title": "Task", "value": context.get("task_instance").task_id, "short": True},
                    {"title": "Execution Date", "value": str(context.get("execution_date")), "short": True},
                ],
            }
        ],
    }
    requests.post(SLACK_WEBHOOK, json=payload)


def _log_audit_event(
    event_type: str,
    event_data: Dict[str, Any],
    **context,
):
    """Log audit event to BigQuery."""
    from google.cloud import bigquery

    client = bigquery.Client(project=PROJECT_ID)
    table_id = f"{PROJECT_ID}.audit.pipeline_events"

    row = {
        "event_id": f"{context['run_id']}_{event_type}_{datetime.utcnow().timestamp()}",
        "product_code": PRODUCT_CODE,
        "dag_id": context["dag"].dag_id,
        "dag_run_id": context["run_id"],
        "task_id": context["task_instance"].task_id,
        "event_type": event_type,
        "event_data": str(event_data),
        "event_timestamp": datetime.utcnow().isoformat(),
        "environment": ENVIRONMENT,
    }

    client.insert_rows_json(table_id, [row])


# =============================================================================
# DAG Definition
# =============================================================================

with DAG(
    dag_id="ebcdic_customer_pipeline",
    default_args=default_args,
    description="Enterprise pipeline for Customer Master from Mainframe - customer",
    schedule="@daily",
    start_date=datetime.strptime("2024-01-01", "%Y-%m-%d"),
    end_date=None,
    catchup=False,
    max_active_runs=1,
    tags=["unknown", "dev", "data-platform"],
    doc_md=__doc__,
    render_template_as_native_obj=True,
) as dag:

    # =========================================================================
    # Pipeline Start/End
    # =========================================================================

    start = EmptyOperator(task_id="start")
    end = EmptyOperator(task_id="end", trigger_rule=TriggerRule.ALL_DONE)

    # =========================================================================
    # Task Group: Pre-Checks (File Sensing, Contract Validation)
    # =========================================================================

    with TaskGroup(group_id="pre_checks") as pre_checks:

        @task(task_id="log_pipeline_start")
        def log_pipeline_start(**context):
            """Log pipeline start event for audit trail."""
            _log_audit_event(
                event_type="pipeline_started",
                event_data={
                    "product_code": PRODUCT_CODE,
                    "processing_mode": PROCESSING_MODE,
                    "source_path": LANDING_PATH,
                },
                **context,
            )
            return {"started_at": datetime.utcnow().isoformat()}

        # File sensor for file-based sources
        wait_for_files = GCSObjectsWithPrefixExistenceSensor(
            task_id="wait_for_files",
            bucket="landing-mainframe",
            prefix="customer/",
            google_cloud_conn_id="google_cloud_default",
            mode="poke",
            poke_interval=60,
            timeout=120 * 60,
            soft_fail=False,
        )

        @task(task_id="validate_contract")
        def validate_contract(**context):
            """
            Validate that source data meets contract requirements.

            Checks:
            - File exists at expected path
            - File name matches pattern
            - File size within bounds
            - Header row present (if expected)
            """
            from google.cloud import storage

            client = storage.Client()
            bucket_name = LANDING_PATH.split("/")[2]
            prefix = "/".join(LANDING_PATH.split("/")[3:])

            bucket = client.bucket(bucket_name)
            blobs = list(bucket.list_blobs(prefix=prefix))

            if not blobs:
                raise AirflowFailException(f"No files found at {LANDING_PATH}")

            # Validate file pattern
            file_pattern = SOURCE_CONFIG.get("file_pattern")
            if file_pattern:
                import re
                pattern = re.compile(file_pattern)
                matching = [b for b in blobs if pattern.match(b.name.split("/")[-1])]
                if not matching:
                    raise AirflowFailException(f"No files match pattern: {file_pattern}")
                blobs = matching

            # Log validation results
            return {
                "files_found": len(blobs),
                "total_size_bytes": sum(b.size for b in blobs),
                "file_names": [b.name for b in blobs[:10]],  # First 10
            }

        @task(task_id="check_schema_version")
        def check_schema_version(**context):
            """Check if schema version matches expected version."""
            # In production, this would query metadata database
            return {
                "schema_version": "1.0.0",
                "is_current": True,
            }

        # Task dependencies within pre_checks
        start_log = log_pipeline_start()
        start_log >> wait_for_files >> validate_contract() >> check_schema_version()

    # =========================================================================
    # Task Group: Landing Zone (Raw File Validation)
    # =========================================================================

    with TaskGroup(group_id="landing_zone") as landing_zone:

        @task(task_id="validate_file_structure")
        def validate_file_structure(**context):
            """
            Validate file structure before processing.

            Checks:
            - Encoding is correct
            - Delimiter is consistent
            - Row count within bounds
            - No corrupted records
            """
            # This would use PySpark or specialized tools
            return {
                "status": "validated",
                "record_count_estimate": 0,  # Placeholder
                "validation_time": datetime.utcnow().isoformat(),
            }

        @task(task_id="validate_copybook")
        def validate_copybook(**context):
            """Validate COBOL copybook matches file layout."""
            # Use Cobrix or custom parser to validate
            return {
                "copybook_valid": True,
                "record_length": SOURCE_CONFIG.get("record_length", 0),
            }

        validate_copybook_task = validate_copybook()

        @task(task_id="stage_landing_files")
        def stage_landing_files(**context):
            """
            Stage landing files with timestamp for processing.

            Creates a snapshot of files to process, preventing
            new files from affecting the current run.
            """
            execution_date = context["execution_date"].strftime("%Y%m%d_%H%M%S")
            staged_path = f"{LANDING_PATH}/_staged/{execution_date}/"

            # In production, this would copy files to staged location
            return {
                "staged_path": staged_path,
                "files_staged": 0,  # Placeholder
            }

        validate_struct = validate_file_structure()
        stage_files = stage_landing_files()

        validate_struct >> validate_copybook_task >> stage_files

    # =========================================================================
    # Task Group: Bronze Zone (Raw Data Ingestion)
    # =========================================================================

    with TaskGroup(group_id="bronze_zone") as bronze_zone:

        bronze_ingest = DataprocSubmitJobOperator(
            task_id="bronze_ingest",
            project_id=PROJECT_ID,
            region=REGION,
            job=_build_spark_job(
                SPARK_JOBS["bronze_ingest"],
                args=[
                    "--source-path", LANDING_PATH,
                    "--target-path", BRONZE_PATH,
                    "--source-format", "ebcdic_copybook",
                    "--processing-mode", PROCESSING_MODE,
                    "--execution-date", "{{ ds }}",
                    "--batch-id", "{{ run_id }}",
                    "--copybook-path", "gs://copybooks/customer_record.cpy",
                ],
                spark_config=SPARK_BRONZE_CONFIG,
            ),
        )

        @task(task_id="validate_bronze_output")
        def validate_bronze_output(**context):
            """Validate bronze ingestion output."""
            return {
                "bronze_validated": True,
                "records_ingested": 0,  # Would come from Spark job metrics
            }

        @task(task_id="log_bronze_metrics")
        def log_bronze_metrics(**context):
            """Log bronze zone metrics for monitoring."""
            _log_audit_event(
                event_type="bronze_complete",
                event_data={
                    "zone": "bronze",
                    "records_processed": 0,  # Placeholder
                },
                **context,
            )

        bronze_ingest >> validate_bronze_output() >> log_bronze_metrics()

    # =========================================================================
    # Task Group: Silver Zone (Transformation & Quality)
    # =========================================================================

    with TaskGroup(group_id="silver_zone") as silver_zone:

        silver_transform = DataprocSubmitJobOperator(
            task_id="silver_transform",
            project_id=PROJECT_ID,
            region=REGION,
            job=_build_spark_job(
                SPARK_JOBS["silver_transform"],
                args=[
                    "--source-path", BRONZE_PATH,
                    "--target-path", SILVER_PATH,
                    "--rejected-path", REJECTED_PATH,
                    "--processing-mode", PROCESSING_MODE,
                    "--load-strategy", LOAD_STRATEGY,
                    "--primary-keys", ",".join(PRIMARY_KEYS),
                    "--execution-date", "{{ ds }}",
                    "--batch-id", "{{ run_id }}",
                ],
                spark_config=SPARK_SILVER_CONFIG,
            ),
        )

        @task(task_id="run_quality_validation")
        def run_quality_validation(**context):
            """
            Run Great Expectations quality validation on silver data.

            Returns quality score and validation details.
            """
            # This would invoke the quality validation Spark job
            # or use the GreatExpectationsManager directly

            # Placeholder - in production, read from Spark job output
            quality_result = {
                "quality_score": 95.5,
                "rules_passed": 18,
                "rules_failed": 2,
                "blocking_failures": 0,
                "records_validated": 10000,
                "records_failed": 50,
            }

            # Push to XCom for quality gate
            context["ti"].xcom_push(key="quality_result", value=quality_result)

            return quality_result

        @task(task_id="log_silver_metrics")
        def log_silver_metrics(**context):
            """Log silver zone metrics."""
            _log_audit_event(
                event_type="silver_complete",
                event_data={
                    "zone": "silver",
                    "quality_score": context["ti"].xcom_pull(
                        task_ids="silver_zone.run_quality_validation",
                        key="quality_result"
                    ).get("quality_score", 0),
                },
                **context,
            )

        silver_transform >> run_quality_validation() >> log_silver_metrics()

    # =========================================================================
    # Task Group: Quality Gate (DQ Score Decision)
    # =========================================================================

    with TaskGroup(group_id="quality_gate") as quality_gate:

        @task.branch(task_id="check_quality_threshold")
        def check_quality_threshold(**context):
            """
            Check if quality score meets threshold.

            Routes to:
            - continue_pipeline: Quality passed
            - quality_failed: Quality below threshold
            """
            quality_result = context["ti"].xcom_pull(
                task_ids="silver_zone.run_quality_validation",
                key="quality_result"
            )

            quality_score = quality_result.get("quality_score", 0)
            blocking_failures = quality_result.get("blocking_failures", 0)

            if blocking_failures > 0:
                return "quality_gate.quality_failed"

            if quality_score >= MIN_QUALITY_SCORE:
                return "quality_gate.quality_passed"
            else:
                if BLOCK_ON_QUALITY_FAILURE:
                    return "quality_gate.quality_failed"
                else:
                    return "quality_gate.quality_warning"

        quality_passed = EmptyOperator(task_id="quality_passed")

        quality_warning = EmptyOperator(task_id="quality_warning")

        @task(task_id="quality_failed", trigger_rule=TriggerRule.NONE_SKIPPED)
        def quality_failed(**context):
            """Handle quality failure."""
            quality_result = context["ti"].xcom_pull(
                task_ids="silver_zone.run_quality_validation",
                key="quality_result"
            )

            _send_slack_notification(
                context,
                f":x: Quality gate failed! Score: {quality_result.get('quality_score', 0):.1f}%"
            )

            if SELF_HEALING_ENABLED:
                # Route to self-healing
                context["ti"].xcom_push(key="trigger_healing", value=True)
            else:
                raise AirflowFailException(
                    f"Quality score {quality_result.get('quality_score', 0)} "
                    f"below threshold {MIN_QUALITY_SCORE}"
                )

        check_threshold = check_quality_threshold()
        check_threshold >> [quality_passed, quality_warning, quality_failed()]

    # =========================================================================
    # Task Group: Gold Zone (Aggregation & Enrichment)
    # =========================================================================

    with TaskGroup(group_id="gold_zone") as gold_zone:

        gold_aggregate = DataprocSubmitJobOperator(
            task_id="gold_aggregate",
            project_id=PROJECT_ID,
            region=REGION,
            job=_build_spark_job(
                SPARK_JOBS["gold_aggregate"],
                args=[
                    "--source-path", SILVER_PATH,
                    "--target-path", GOLD_PATH,
                    "--partition-columns", ",".join(PARTITION_COLUMNS),
                    "--execution-date", "{{ ds }}",
                    "--batch-id", "{{ run_id }}",
                ],
                spark_config=SPARK_GOLD_CONFIG,
            ),
        )

        @task(task_id="validate_gold_output")
        def validate_gold_output(**context):
            """Validate gold aggregation output."""
            return {"gold_validated": True}

        @task(task_id="log_gold_metrics")
        def log_gold_metrics(**context):
            """Log gold zone metrics."""
            _log_audit_event(
                event_type="gold_complete",
                event_data={"zone": "gold"},
                **context,
            )

        gold_aggregate >> validate_gold_output() >> log_gold_metrics()

    # =========================================================================
    # Task Group: Trusted Zone (Publication to Targets)
    # =========================================================================

    with TaskGroup(group_id="trusted_zone") as trusted_zone:


        # Default: Copy to trusted zone GCS
        copy_to_trusted = GCSToGCSOperator(
            task_id="copy_to_trusted",
            source_bucket=GOLD_PATH.split("/")[2],
            source_object="/".join(GOLD_PATH.split("/")[3:]) + "/*",
            destination_bucket=TRUSTED_PATH.split("/")[2],
            destination_object="/".join(TRUSTED_PATH.split("/")[3:]) + "/",
        )

        @task(task_id="certify_data_product")
        def certify_data_product(**context):
            """
            Mark data product as certified for the execution date.

            Updates metadata to indicate this dataset is production-ready.
            """
            return {
                "certified": True,
                "certification_time": datetime.utcnow().isoformat(),
            }

        @task(task_id="log_trusted_metrics")
        def log_trusted_metrics(**context):
            """Log trusted zone publication metrics."""
            _log_audit_event(
                event_type="trusted_complete",
                event_data={
                    "zone": "trusted",
                    "certified": True,
                },
                **context,
            )

        # Dependencies within trusted zone
        copy_to_trusted >> certify_data_product()
        certify_data_product() >> log_trusted_metrics()

    # =========================================================================
    # Task Group: Self-Healing (Automatic Error Recovery)
    # =========================================================================

    with TaskGroup(group_id="self_healing") as self_healing:

        @task.branch(task_id="check_healing_needed")
        def check_healing_needed(**context):
            """Check if self-healing should be triggered."""
            trigger_healing = context["ti"].xcom_pull(
                key="trigger_healing",
                default=False
            )

            if trigger_healing:
                return "self_healing.diagnose_failure"
            else:
                return "self_healing.no_healing_needed"

        no_healing_needed = EmptyOperator(task_id="no_healing_needed")

        @task(task_id="diagnose_failure")
        def diagnose_failure(**context):
            """
            Use LLM agent to diagnose the failure.

            Analyzes:
            - Error logs
            - Data quality results
            - Schema changes
            - Historical patterns
            """
            # This would call the SelfHealingAgent
            diagnosis = {
                "error_type": "data_quality_failure",
                "root_cause": "Schema drift detected in source",
                "confidence": 0.85,
                "recommended_action": "schema_update",
            }

            context["ti"].xcom_push(key="diagnosis", value=diagnosis)
            return diagnosis

        @task(task_id="apply_remediation")
        def apply_remediation(**context):
            """
            Apply remediation based on diagnosis.

            Actions:
            - schema_update: Update schema to match source
            - retry: Simple retry with same config
            - config_adjust: Adjust Spark/processing config
            - skip: Skip bad records and continue
            - escalate: Alert human for intervention
            """
            diagnosis = context["ti"].xcom_pull(
                task_ids="self_healing.diagnose_failure",
                key="diagnosis"
            )

            action = diagnosis.get("recommended_action", "escalate")

            if action == "retry":
                return {"action": "retry", "result": "scheduled"}
            elif action == "schema_update":
                # In production, this would update the schema
                return {"action": "schema_update", "result": "applied"}
            elif action == "escalate":
                _send_slack_notification(
                    context,
                    f":warning: Self-healing escalated to human.\n"
                    f"Diagnosis: {diagnosis.get('root_cause')}"
                )
                return {"action": "escalate", "result": "notified"}
            else:
                return {"action": action, "result": "unknown"}

        @task(task_id="verify_remediation")
        def verify_remediation(**context):
            """Verify that remediation was successful."""
            return {"verified": True}

        @task(task_id="log_healing_event")
        def log_healing_event(**context):
            """Log self-healing event for audit and learning."""
            diagnosis = context["ti"].xcom_pull(
                task_ids="self_healing.diagnose_failure",
                key="diagnosis"
            )

            _log_audit_event(
                event_type="self_healing",
                event_data=diagnosis,
                **context,
            )

        check = check_healing_needed()
        diagnose = diagnose_failure()
        remediate = apply_remediation()
        verify = verify_remediation()
        log_healing = log_healing_event()

        check >> [no_healing_needed, diagnose]
        diagnose >> remediate >> verify >> log_healing

    # =========================================================================
    # Task Group: Post-Processing (Cleanup, Notifications)
    # =========================================================================

    with TaskGroup(group_id="post_processing") as post_processing:

        @task(task_id="archive_landing_files")
        def archive_landing_files(**context):
            """
            Archive processed landing files.

            Moves files to archive with date prefix for retention.
            """
            execution_date = context["execution_date"].strftime("%Y/%m/%d")
            archive_destination = f"{ARCHIVE_PATH}/{execution_date}/"

            # In production, this would move files
            return {
                "archived_to": archive_destination,
                "files_archived": 0,
            }

        @task(task_id="update_lineage")
        def update_lineage(**context):
            """
            Update data lineage graph.

            Records:
            - Source -> Bronze -> Silver -> Gold -> Trusted transformations
            - Quality validation results
            - Schema versions used
            """
            # This would update a lineage store like OpenLineage
            return {"lineage_updated": True}

        @task(task_id="send_success_notification")
        def send_success_notification(**context):
            """Send success notification to stakeholders."""
            quality_result = context["ti"].xcom_pull(
                task_ids="silver_zone.run_quality_validation",
                key="quality_result"
            ) or {}

            _send_slack_notification(
                context,
                f":white_check_mark: Pipeline completed successfully!\n"
                f"Quality Score: {quality_result.get('quality_score', 'N/A')}%"
            )

        @task(task_id="log_pipeline_complete")
        def log_pipeline_complete(**context):
            """Log pipeline completion for audit."""
            _log_audit_event(
                event_type="pipeline_complete",
                event_data={
                    "status": "success",
                    "completed_at": datetime.utcnow().isoformat(),
                },
                **context,
            )

        (
            archive_landing_files()
            >> update_lineage()
            >> send_success_notification()
            >> log_pipeline_complete()
        )

    # =========================================================================
    # Error Handling
    # =========================================================================

    @task(task_id="handle_pipeline_failure", trigger_rule=TriggerRule.ONE_FAILED)
    def handle_pipeline_failure(**context):
        """Handle pipeline failure - send alerts and log."""
        task_instance = context.get("task_instance")
        exception = context.get("exception")

        _send_slack_notification(
            context,
            f":x: Pipeline failed!\nTask: {task_instance.task_id}\nError: {str(exception)}"
        )

        _log_audit_event(
            event_type="pipeline_failed",
            event_data={
                "task_id": task_instance.task_id,
                "error": str(exception),
            },
            **context,
        )

    failure_handler = handle_pipeline_failure()

    # =========================================================================
    # Task Dependencies (Main Flow)
    # =========================================================================

    # Main happy path
    (
        start
        >> pre_checks
        >> landing_zone
        >> bronze_zone
        >> silver_zone
        >> quality_gate
    )

    # Quality gate routing
    quality_gate >> gold_zone >> trusted_zone >> post_processing >> end

    # Self-healing path (triggered by quality failure)
    quality_gate >> self_healing >> end

    # Error handling (triggered by any failure)
    [bronze_zone, silver_zone, gold_zone, trusted_zone] >> failure_handler
