"""
Example Medallion Architecture DAG - Auto-generated by Data Agent
Pipeline: example_sales_pipeline
Domain: sales
Generated: 2024-01-19

This DAG orchestrates a complete medallion data pipeline:
Bronze (raw ingest) → Silver (transform) → Gold (aggregates to BigQuery)
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator
from airflow.providers.google.cloud.operators.dataproc import (
    DataprocSubmitJobOperator,
    DataprocCreateClusterOperator,
    DataprocDeleteClusterOperator,
)
from airflow.providers.google.cloud.sensors.gcs import GCSObjectExistenceSensor
from airflow.utils.trigger_rule import TriggerRule

# Configuration
PROJECT_ID = "{{ var.value.gcp_project_id }}"
REGION = "{{ var.value.gcp_region | default('us-central1') }}"
CLUSTER_NAME = "data-agent-dataproc-{{ ds_nodash }}"
BUCKET = "{{ var.value.data_bucket }}"
SPARK_BUCKET = f"gs://{PROJECT_ID}-gold/spark"

default_args = {
    "owner": "data-platform",
    "depends_on_past": False,
    "email_on_failure": True,
    "email_on_retry": False,
    "retries": 3,
    "retry_delay": timedelta(minutes=5),
    "email": ["data-platform@example.com"],
}

# Cluster configuration for Dataproc
CLUSTER_CONFIG = {
    "master_config": {
        "num_instances": 1,
        "machine_type_uri": "n1-standard-4",
        "disk_config": {"boot_disk_type": "pd-standard", "boot_disk_size_gb": 500},
    },
    "worker_config": {
        "num_instances": 2,
        "machine_type_uri": "n1-standard-4",
        "disk_config": {"boot_disk_type": "pd-standard", "boot_disk_size_gb": 500},
    },
    "software_config": {
        "image_version": "2.1-debian11",
        "properties": {
            "spark:spark.jars.packages": "io.delta:delta-core_2.12:2.4.0",
            "spark:spark.sql.extensions": "io.delta.sql.DeltaSparkSessionExtension",
            "spark:spark.sql.catalog.spark_catalog": "org.apache.spark.sql.delta.catalog.DeltaCatalog",
        },
    },
}


def generate_batch_id(**context):
    """Generate unique batch ID for this run."""
    return f"{context['dag'].dag_id}_{context['ds_nodash']}_{context['run_id'][:8]}"


with DAG(
    dag_id="example_sales_medallion_pipeline",
    default_args=default_args,
    description="Sales data medallion pipeline: Bronze → Silver → Gold",
    schedule="0 6 * * *",  # Daily at 6 AM
    start_date=datetime(2024, 1, 1),
    catchup=False,
    tags=["data-platform", "medallion", "sales", "auto-generated"],
    doc_md=__doc__,
    max_active_runs=1,
) as dag:

    # Task 1: Generate batch ID
    generate_batch = PythonOperator(
        task_id="generate_batch_id",
        python_callable=generate_batch_id,
    )

    # Task 2: Check if source file exists
    check_source = GCSObjectExistenceSensor(
        task_id="check_source_file",
        bucket=BUCKET,
        object="landing/sales/{{ ds }}/sales_data.parquet",
        timeout=600,
        poke_interval=60,
        mode="reschedule",
    )

    # Task 3: Create Dataproc cluster
    create_cluster = DataprocCreateClusterOperator(
        task_id="create_dataproc_cluster",
        project_id=PROJECT_ID,
        cluster_name=CLUSTER_NAME,
        region=REGION,
        cluster_config=CLUSTER_CONFIG,
    )

    # Task 4: Bronze layer - Raw ingest
    bronze_ingest = DataprocSubmitJobOperator(
        task_id="bronze_ingest",
        project_id=PROJECT_ID,
        region=REGION,
        cluster_name=CLUSTER_NAME,
        job={
            "reference": {"job_id": "bronze_{{ ds_nodash }}_{{ run_id[:8] }}"},
            "placement": {"cluster_name": CLUSTER_NAME},
            "pyspark_job": {
                "main_python_file_uri": f"{SPARK_BUCKET}/bronze_ingest.py",
                "args": [
                    "--source-path", f"gs://{BUCKET}/landing/sales/{{{{ ds }}}}/",
                    "--batch-id", "{{ ti.xcom_pull(task_ids='generate_batch_id') }}",
                    "--execution-date", "{{ ds }}",
                ],
            },
        },
    )

    # Task 5: Silver layer - Transform and clean
    silver_transform = DataprocSubmitJobOperator(
        task_id="silver_transform",
        project_id=PROJECT_ID,
        region=REGION,
        cluster_name=CLUSTER_NAME,
        job={
            "reference": {"job_id": "silver_{{ ds_nodash }}_{{ run_id[:8] }}"},
            "placement": {"cluster_name": CLUSTER_NAME},
            "pyspark_job": {
                "main_python_file_uri": f"{SPARK_BUCKET}/silver_transform.py",
                "args": [
                    "--batch-id", "{{ ti.xcom_pull(task_ids='generate_batch_id') }}",
                    "--execution-date", "{{ ds }}",
                ],
            },
        },
    )

    # Task 6: Gold layer - Load to BigQuery
    gold_load = DataprocSubmitJobOperator(
        task_id="gold_load_bq",
        project_id=PROJECT_ID,
        region=REGION,
        cluster_name=CLUSTER_NAME,
        job={
            "reference": {"job_id": "gold_{{ ds_nodash }}_{{ run_id[:8] }}"},
            "placement": {"cluster_name": CLUSTER_NAME},
            "pyspark_job": {
                "main_python_file_uri": f"{SPARK_BUCKET}/gold_load_bq.py",
                "args": [
                    "--batch-id", "{{ ti.xcom_pull(task_ids='generate_batch_id') }}",
                    "--execution-date", "{{ ds }}",
                    "--target-dataset", "gold_sales",
                    "--target-table", "daily_sales_summary",
                ],
            },
        },
    )

    # Task 7: Delete cluster (always runs)
    delete_cluster = DataprocDeleteClusterOperator(
        task_id="delete_dataproc_cluster",
        project_id=PROJECT_ID,
        cluster_name=CLUSTER_NAME,
        region=REGION,
        trigger_rule=TriggerRule.ALL_DONE,
    )

    # Define task dependencies
    generate_batch >> check_source >> create_cluster
    create_cluster >> bronze_ingest >> silver_transform >> gold_load >> delete_cluster
