"""
APEX Data Agent - P01: FILE_MEDALLION Pipeline Pattern
Pattern: FILE → BRONZE → SILVER → GOLD

This is the standard file ingestion pattern for the medallion architecture.
Source files are ingested to Bronze, transformed to Silver, and aggregated to Gold.

Generated by APEX Data Agent
Contract ID: CONTRACT_426B3F3D
Feed ID: FEED_89CBE419
"""

from datetime import datetime, timedelta
from airflow import DAG
from airflow.operators.python import PythonOperator, BranchPythonOperator
from airflow.operators.empty import EmptyOperator
from airflow.utils.trigger_rule import TriggerRule

# Import APEX dag_utilities
from dag_utilities.core import MetadataClient, ExecutionContext, APEXConfig
from dag_utilities.logging import LineageTracker
from dag_utilities.remediation import SelfHealer, RetryHandler
from dag_utilities.pipeline import pipeline_tasks


# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

FEED_ID = "FEED_89CBE419"
CONTRACT_ID = "CONTRACT_426B3F3D"
DOMAIN = "default"

# Metadata-driven configuration
config = APEXConfig.from_environment()
metadata = MetadataClient(config.metadata_db_url)
retry_handler = RetryHandler(max_retries=3)

# Default arguments
default_args = {
    "owner": "apex-data-agent",
    "depends_on_past": False,
    "email": [],
    "email_on_failure": True,
    "email_on_retry": False,
    **retry_handler.get_airflow_retry_args(),
}


# ═══════════════════════════════════════════════════════════════════════════════
# DAG DEFINITION
# ═══════════════════════════════════════════════════════════════════════════════

with DAG(
    dag_id="mainframe_customer_ebcdic",
    default_args=default_args,
    description="File Medallion Pipeline - FEED_89CBE419",
    schedule_interval="@daily",
    start_date=datetime(2026, 1, 31),
    catchup=False,
    max_active_runs=1,
    tags=["apex", "medallion", "default", "FEED_89CBE419"],
) as dag:

    # ═══════════════════════════════════════════════════════════════════════════
    # TASK DEFINITIONS
    # ═══════════════════════════════════════════════════════════════════════════

    start = EmptyOperator(task_id="start")

    init_exec = PythonOperator(
        task_id="initialize_execution",
        python_callable=pipeline_tasks.initialize_execution,
        op_kwargs={
            "metadata": metadata,
            "feed_id": FEED_ID,
            "contract_id": CONTRACT_ID,
            "execution_mode": "FILE_MEDALLION",
        },
        on_failure_callback=SelfHealer().on_task_failure,
    )

    check_source = PythonOperator(
        task_id="check_source_file",
        python_callable=pipeline_tasks.check_source_file,
        op_kwargs={
            "metadata": metadata,
            "feed_id": FEED_ID,
        },
        on_failure_callback=SelfHealer().on_task_failure,
    )

    raw_bronze = PythonOperator(
        task_id="raw_to_bronze",
        python_callable=pipeline_tasks.submit_zone_job,
        op_kwargs={
            "config": config,
            "job_name": "raw_to_bronze",
            "job_path": "spark_jobs/raw_to_bronze.py",
            "feed_id": FEED_ID,
            "contract_id": CONTRACT_ID,
            "metrics_xcom_key": "bronze_metrics",
        },
        on_failure_callback=SelfHealer().on_task_failure,
    )

    bronze_validation = BranchPythonOperator(
        task_id="bronze_schema_validation",
        python_callable=pipeline_tasks.run_ge_validation,
        op_kwargs={
            "config": config,
            "feed_id": FEED_ID,
            "contract_id": CONTRACT_ID,
            "zone_level": "BRONZE",
            "validation_type": "SCHEMA",
            "pass_task": "bronze_to_silver",
            "fail_task": "handle_validation_failure",
        },
    )

    bronze_silver = PythonOperator(
        task_id="bronze_to_silver",
        python_callable=pipeline_tasks.submit_zone_job,
        op_kwargs={
            "config": config,
            "job_name": "bronze_to_silver",
            "job_path": "spark_jobs/bronze_to_silver.py",
            "feed_id": FEED_ID,
            "contract_id": CONTRACT_ID,
            "metrics_xcom_key": "silver_metrics",
        },
        on_failure_callback=SelfHealer().on_task_failure,
    )

    silver_validation = BranchPythonOperator(
        task_id="silver_semantic_validation",
        python_callable=pipeline_tasks.run_ge_validation,
        op_kwargs={
            "config": config,
            "feed_id": FEED_ID,
            "contract_id": CONTRACT_ID,
            "zone_level": "SILVER",
            "validation_type": "SEMANTIC",
            "pass_task": "silver_to_gold",
            "fail_task": "handle_validation_failure",
        },
    )

    silver_gold = PythonOperator(
        task_id="silver_to_gold",
        python_callable=pipeline_tasks.submit_zone_job,
        op_kwargs={
            "config": config,
            "job_name": "silver_to_gold",
            "job_path": "spark_jobs/silver_to_gold.py",
            "feed_id": FEED_ID,
            "contract_id": CONTRACT_ID,
            "metrics_xcom_key": "gold_metrics",
        },
        on_failure_callback=SelfHealer().on_task_failure,
    )

    quality_checks = PythonOperator(
        task_id="run_quality_checks",
        python_callable=pipeline_tasks.run_quality_checks,
        op_kwargs={
            "metadata": metadata,
            "contract_id": CONTRACT_ID,
            "check_type": "all",
            "pass_task": "finalize_execution",
            "fail_task": "handle_validation_failure",
        },
    )

    validation_failure = PythonOperator(
        task_id="handle_validation_failure",
        python_callable=pipeline_tasks.handle_validation_failure,
        trigger_rule=TriggerRule.ONE_FAILED,
    )

    finalize = PythonOperator(
        task_id="finalize_execution",
        python_callable=pipeline_tasks.finalize_execution,
        op_kwargs={
            "metadata": metadata,
            "metric_keys": ["bronze_metrics", "silver_metrics", "gold_metrics"],
            "lineage_fn": lambda execution_id, context: LineageTracker().track_pipeline_lineage(
                execution_id=execution_id,
                contract_id=CONTRACT_ID,
            ),
        },
        trigger_rule=TriggerRule.ALL_SUCCESS,
    )

    notify = PythonOperator(
        task_id="send_notifications",
        python_callable=pipeline_tasks.send_notifications,
        op_kwargs={
            "pipeline_name": "mainframe_customer_ebcdic",
            "feed_id": FEED_ID,
        },
        trigger_rule=TriggerRule.ALL_DONE,
    )

    end = EmptyOperator(
        task_id="end",
        trigger_rule=TriggerRule.ALL_DONE,
    )

    # ═══════════════════════════════════════════════════════════════════════════
    # UPSTREAM DEPENDENCY SENSORS (optional)
    # ═══════════════════════════════════════════════════════════════════════════

    # ═══════════════════════════════════════════════════════════════════════════
    # TASK DEPENDENCIES
    # ═══════════════════════════════════════════════════════════════════════════
    start >> init_exec
    init_exec >> check_source >> raw_bronze >> bronze_validation

    bronze_validation >> bronze_silver >> silver_validation
    bronze_validation >> validation_failure

    silver_validation >> silver_gold >> quality_checks >> finalize
    silver_validation >> validation_failure

    finalize >> notify >> end
    validation_failure >> notify >> end
