"""
APEX Data Agent - File Ingest Pipeline (v2)
Pattern: GCS File → Landing → Bronze → Silver → Gold

Generated by APEX Data Agent (deterministic)
Feed Group: fg_sales_daily
DAG ID: sales_daily_csv_ingest
Domain: sales
"""

import os
from datetime import datetime, timedelta

from airflow import DAG
from airflow.operators.python import PythonOperator, BranchPythonOperator
from airflow.operators.empty import EmptyOperator
from airflow.utils.trigger_rule import TriggerRule
from airflow.utils.task_group import TaskGroup

from dag_utilities.core import MetadataClient, ExecutionContext, APEXConfig
from dag_utilities.pipeline import pipeline_tasks
from dag_utilities.sources.file_source import get_gcs_file_sensor, list_source_files
from dag_utilities.common.zone_transition import submit_dataproc_job
from dag_utilities.common.sql_executor import run_bq_query
from dag_utilities.validation import SchemaValidator, SemanticValidator
from dag_utilities.notification import EmailNotifier
from dag_utilities.logging import AuditLogger
from dag_utilities.remediation import SelfHealer, RetryHandler


# ═══════════════════════════════════════════════════════════════════════════════
# CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

FEED_GROUP_ID = "fg_sales_daily"
DAG_ID = "sales_daily_csv_ingest"
DOMAIN = "sales"
ENVIRONMENT = os.getenv("APEX_ENVIRONMENT", "dev")

config = APEXConfig.from_environment()
metadata = MetadataClient(config.metadata_db_url)
retry_handler = RetryHandler(max_retries=3)
audit = AuditLogger(metadata)

# Per-environment schedule
SCHEDULES = {"dev": "@daily", "prod": "0 6 * * *"}
SCHEDULE = SCHEDULES.get(ENVIRONMENT, "@daily")

# Per-environment notifications
NOTIFICATIONS = {"prod": ["data-team@company.com"]}
NOTIFY_EMAILS = NOTIFICATIONS.get(ENVIRONMENT, [])

default_args = {
    "owner": "apex-data-agent",
    "depends_on_past": False,
    "email": NOTIFY_EMAILS,
    "email_on_failure": True,
    **retry_handler.get_airflow_retry_args(),
}


# ═══════════════════════════════════════════════════════════════════════════════
# DAG DEFINITION
# ═══════════════════════════════════════════════════════════════════════════════

with DAG(
    dag_id=DAG_ID,
    default_args=default_args,
    description="Daily sales CSV file ingest pipeline",
    schedule=SCHEDULE,
    start_date=datetime(2024, 1, 1),
    catchup=False,
    max_active_runs=1,
    tags=["apex", "v2", "file", "sales", "sales", "csv", "daily"],
) as dag:

    start = EmptyOperator(task_id="start")

    init_exec = PythonOperator(
        task_id="initialize_execution",
        python_callable=pipeline_tasks.initialize_execution,
        op_kwargs={
            "metadata": metadata,
            "feed_group_id": FEED_GROUP_ID,
            "execution_mode": "FILE_INGEST",
        },
    )


    # ═══════════════════════════════════════════════════════════════════════
    # FEED TASK GROUPS
    # ═══════════════════════════════════════════════════════════════════════

    with TaskGroup(group_id="feed_daily_sales") as tg_daily_sales:

        # --- File Sensing ---
        sense_files = PythonOperator(
            task_id="sense_files",
            python_callable=list_source_files,
            op_kwargs={
                "source_config": {"bucket": "data-lake-raw", "pattern": "*.csv", "prefix": "inbound/sales/"},
                "file_format": "csv",
            },
        )

        # --- Source to Landing ---
        source_to_landing = PythonOperator(
            task_id="source_to_landing",
            python_callable=submit_dataproc_job,
            op_kwargs={
                "job_name": "source_to_landing",
                "job_path": "spark_jobs/v2/ingest_source_to_landing.py",
                "args": {
                    "--feed-id": "feed_daily_sales",
                    "--batch-id": "{{ ds_nodash }}",
                    "--source-type": "gcs_file",
                    "--source-path": "data-lake-raw/inbound/sales/",
                    "--file-format": "csv",
                    "--target-path": "gs://datalake/landing/sales/daily_sales/{{ ds }}/",
                    "--metadata-db": config.metadata_db_url,
                    "--delimiter": ",",
                    "--header-rows": "1",
                    "--footer-rows": "0",
                    "--encoding": "UTF-8",
                },
            },
            on_failure_callback=SelfHealer().on_task_failure,
        )

        # --- Schema Validation ---
        schema_validation = BranchPythonOperator(
            task_id="schema_validation",
            python_callable=pipeline_tasks.run_ge_validation,
            op_kwargs={
                "config": config,
                "feed_id": "feed_daily_sales",
                "zone_level": "LANDING",
                "validation_type": "SCHEMA",
                "pass_task": "feed_daily_sales.landing_to_bronze",
                "fail_task": "feed_daily_sales.handle_validation_failure",
            },
        )

        # --- Landing to Bronze ---
        landing_to_bronze = PythonOperator(
            task_id="landing_to_bronze",
            python_callable=submit_dataproc_job,
            op_kwargs={
                "job_name": "landing_to_bronze",
                "job_path": "spark_jobs/v2/promote_landing_to_bronze.py",
                "args": {
                    "--feed-id": "feed_daily_sales",
                    "--contract-id": "feed_daily_sales",
                    "--execution-id": "{{ ti.xcom_pull(key='execution_id') }}",
                    "--execution-date": "{{ ds }}",
                    "--metadata-db": config.metadata_db_url,
                    "--landing-path": "gs://datalake/landing/sales/daily_sales/{{ ds }}/",
                    "--bronze-path": "gs://datalake/bronze/sales/daily_sales/{{ ds }}/",
                    "--bq-table": "${GCP_PROJECT}.bronze_sales.daily_sales",
                },
            },
            on_failure_callback=SelfHealer().on_task_failure,
        )

        # --- Semantic Validation ---
        semantic_validation = BranchPythonOperator(
            task_id="semantic_validation",
            python_callable=pipeline_tasks.run_ge_validation,
            op_kwargs={
                "config": config,
                "feed_id": "feed_daily_sales",
                "zone_level": "BRONZE",
                "validation_type": "SEMANTIC",
                "pass_task": "feed_daily_sales.bronze_to_silver",
                "fail_task": "feed_daily_sales.handle_validation_failure",
            },
        )

        # --- Bronze to Silver ---
        bronze_to_silver = PythonOperator(
            task_id="bronze_to_silver",
            python_callable=submit_dataproc_job,
            op_kwargs={
                "job_name": "bronze_to_silver",
                "job_path": "spark_jobs/v2/promote_bronze_to_silver.py",
                "args": {
                    "--feed-id": "feed_daily_sales",
                    "--contract-id": "feed_daily_sales",
                    "--execution-id": "{{ ti.xcom_pull(key='execution_id') }}",
                    "--execution-date": "{{ ds }}",
                    "--metadata-db": config.metadata_db_url,
                    "--bronze-path": "gs://datalake/bronze/sales/daily_sales/{{ ds }}/",
                    "--silver-path": "gs://datalake/silver/sales/daily_sales/{{ ds }}/",
                    "--business-keys": "order_id",
                    "--watermark-column": "order_date",
                    "--bq-table": "${GCP_PROJECT}.silver_sales.daily_sales",
                },
            },
            on_failure_callback=SelfHealer().on_task_failure,
        )

        # --- Silver to Gold ---
        silver_to_gold = PythonOperator(
            task_id="silver_to_gold",
            python_callable=submit_dataproc_job,
            op_kwargs={
                "job_name": "silver_to_gold",
                "job_path": "spark_jobs/v2/build_gold_layer.py",
                "args": {
                    "--feed-id": "feed_daily_sales",
                    "--contract-id": "feed_daily_sales",
                    "--execution-id": "{{ ti.xcom_pull(key='execution_id') }}",
                    "--execution-date": "{{ ds }}",
                    "--metadata-db": config.metadata_db_url,
                    "--silver-path": "gs://datalake/silver/sales/daily_sales/{{ ds }}/",
                    "--gold-path": "gs://datalake/gold/sales/daily_sales/{{ ds }}/",
                    "--model-type": "flat",
                    "--business-keys": "order_id",
                    "--bq-table": "${GCP_PROJECT}.gold_sales.daily_sales",
                },
            },
            on_failure_callback=SelfHealer().on_task_failure,
        )



        # --- Audit ---
        audit_log = PythonOperator(
            task_id="audit_log",
            python_callable=pipeline_tasks.audit_execution,
            op_kwargs={
                "metadata": metadata,
                "feed_id": "feed_daily_sales",
            },
        )

        # --- Validation Failure Handler ---
        handle_validation_failure = PythonOperator(
            task_id="handle_validation_failure",
            python_callable=pipeline_tasks.handle_validation_failure,
            trigger_rule=TriggerRule.ONE_FAILED,
        )

        # --- Task Dependencies (within TaskGroup) ---
        sense_files >> source_to_landing >> schema_validation
        schema_validation >> landing_to_bronze >> semantic_validation
        semantic_validation >> bronze_to_silver >> silver_to_gold

        silver_to_gold >> audit_log

        schema_validation >> handle_validation_failure
        semantic_validation >> handle_validation_failure


    # ═══════════════════════════════════════════════════════════════════════
    # DUPLICATE DETECTION
    # ═══════════════════════════════════════════════════════════════════════
    check_duplicates = BranchPythonOperator(
        task_id="check_duplicates",
        python_callable=pipeline_tasks.check_duplicate_files,
        op_kwargs={"metadata": metadata, "feed_group_id": FEED_GROUP_ID},
    )


    # ═══════════════════════════════════════════════════════════════════════
    # FINALIZE & NOTIFY
    # ═══════════════════════════════════════════════════════════════════════
    finalize = PythonOperator(
        task_id="finalize",
        python_callable=pipeline_tasks.finalize_execution,
        op_kwargs={
            "metadata": metadata,
            "metric_keys": ["landing_metrics", "bronze_metrics", "silver_metrics", "gold_metrics"],
        },
        trigger_rule=TriggerRule.ALL_SUCCESS,
    )

    notify = PythonOperator(
        task_id="send_notifications",
        python_callable=pipeline_tasks.send_notifications,
        op_kwargs={
            "feed_group_id": FEED_GROUP_ID,
            "dag_id": DAG_ID,
            "emails": NOTIFY_EMAILS,
        },
        trigger_rule=TriggerRule.ALL_DONE,
    )

    end = EmptyOperator(
        task_id="end",
        trigger_rule=TriggerRule.ALL_DONE,
    )

    # ═══════════════════════════════════════════════════════════════════════
    # DAG-LEVEL DEPENDENCIES
    # ═══════════════════════════════════════════════════════════════════════
    start >> init_exec

    init_exec >> tg_daily_sales
    tg_daily_sales >> finalize

    finalize >> notify >> end
