#!/bin/bash
# Script to push generated artifacts to sam2881/enterprise-data-pipelines
#
# Prerequisites:
#   1. GitHub CLI installed: sudo apt install gh
#   2. Authenticate: gh auth login
#   OR
#   Set GITHUB_TOKEN environment variable

set -e

REPO_URL="https://github.com/sam2881/enterprise-data-pipelines.git"
ARTIFACTS_DIR="/tmp/enterprise-data-pipelines"
WORK_DIR="/tmp/enterprise-data-pipelines-repo"

echo "=========================================="
echo " Push Artifacts to Enterprise Data Pipelines"
echo "=========================================="

# Check for GitHub authentication
if ! gh auth status &>/dev/null; then
    if [ -z "$GITHUB_TOKEN" ]; then
        echo "ERROR: Not authenticated with GitHub"
        echo ""
        echo "Please authenticate using one of these methods:"
        echo ""
        echo "Option 1 - GitHub CLI:"
        echo "  gh auth login"
        echo ""
        echo "Option 2 - Personal Access Token:"
        echo "  export GITHUB_TOKEN=your_token_here"
        echo "  Then re-run this script"
        echo ""
        exit 1
    fi
fi

# Clean up any existing work directory
rm -rf "$WORK_DIR"

echo ""
echo "Step 1: Cloning repository..."
if [ -n "$GITHUB_TOKEN" ]; then
    git clone "https://${GITHUB_TOKEN}@github.com/sam2881/enterprise-data-pipelines.git" "$WORK_DIR"
else
    gh repo clone sam2881/enterprise-data-pipelines "$WORK_DIR"
fi

cd "$WORK_DIR"

echo ""
echo "Step 2: Deleting all previous files..."
# Remove everything except .git directory
find . -mindepth 1 -maxdepth 1 ! -name '.git' -exec rm -rf {} +

echo ""
echo "Step 3: Copying generated artifacts..."
cp -r "$ARTIFACTS_DIR"/* .
cp -r "$ARTIFACTS_DIR"/.github .

echo ""
echo "Step 4: Staging changes..."
git add -A

echo ""
echo "Step 5: Checking for changes..."
if git diff --staged --quiet; then
    echo "No changes to commit"
    exit 0
fi

echo ""
echo "Files to be committed:"
git status --short

echo ""
echo "Step 6: Creating commit..."
git commit -m "feat: Add generated pipeline artifacts from Data Agent V2

- metadata/insert_metadata_*.sql: Full schema registration
- metadata/update_metadata_*.sql: Schema evolution templates
- dags/pipeline_*.py: Airflow orchestration DAGs
- spark_jobs/common/: Reusable medallion processors
- .github/workflows/deploy.yml: CI/CD for GCP deployment

Generated by Enterprise Data Engineer Agent V2
Metadata-driven architecture - all config from PostgreSQL

Co-Authored-By: Claude Opus 4.5 <noreply@anthropic.com>"

echo ""
echo "Step 7: Pushing to GitHub..."
git push origin main

echo ""
echo "=========================================="
echo " SUCCESS! Artifacts pushed to GitHub"
echo "=========================================="
echo ""
echo "Repository: https://github.com/sam2881/enterprise-data-pipelines"
echo ""
echo "CI/CD pipeline will now:"
echo "  1. Run tests"
echo "  2. Deploy to GCP"
echo "  3. Trigger Airflow DAG"
echo ""
echo "Monitor the workflow at:"
echo "  https://github.com/sam2881/enterprise-data-pipelines/actions"
echo ""
